apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tour
  template:
    metadata:
      labels:
        app: tour
    spec:
      containers:
        - name: tour
          image: sidhopant/tour-service:v0.0.2
          ports:
            - containerPort: 80
